[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
    -Wall
    -Wextra
    -Werror
    -Wno-missing-field-initializers
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1    
    -DTFT_WIDTH=240       ; Ανάλυση οθόνης
    -DTFT_HEIGHT=320      ; Ανάλυση οθόνης
    -DTFT_MOSI=23         ; Pin 23 -> MOSI
    -DTFT_SCLK=18         ; Pin 18 -> SCLK (CLK)
    -DTFT_CS=15           ; Pin 15 -> CS
    -DTFT_DC=2            ; Pin 2 -> DC (RS/A0)
    -DTFT_RST=4           ; Pin 4 -> Reset
    -DTFT_BL=32           ; Pin 32 -> Backlight (αν το έχεις συνδέσει)
    -DLOAD_GLCD=1         ; Φόρτωση γραμματοσειρών
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
lib_deps = 
    bodmer/TFT_eSPI @ =2.5.43